rootPath: "/log/ncl-batch/"
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,shutdown,info
spring:
  profiles:
    active: uat
  ds:
    jndi: java:jboss/datasources/ncldb
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    generate-ddl: false
    properties:
      hibernate:
        default_schema: "ncl_apuser"
        max_fetch_depth: 3
        jdbc:
          fetch_size: 50
          batch_size: 30
        show_sql: false
        format_sql: false
  log:
    path: "${rootPath}log/"
  application:
    name: ncl-batch
    rec: true
    fsapSyncFg: true
  fsapSyncSftp:
    host: 10.1.11.47
    port: 22
    usr: ncl
    pw: userP@ssw0rd
    poolsize: 20
    timeout: 20000
    localroot: "${rootPath}BH/"
    remoteroot: /NCL/

server:
  port: 9080
  address: 0.0.0.0
  compression:
    enabled: true
  hostname: ${HOSTNAME:default-hostname}

grpc:
  server:
    port: 50001
    address: "0.0.0.0"
    corePoolSize: 50
    maxPoolSize: 200
    threadQueueSize: 200
  runtime:
    port: 50002
    address: "10.1.2.17"
  common:
    port: 50002
    address: "10.1.2.18"

batch:
  name: ncl-batch
  corePoolSize: 25
  maxPoolSize: 100
  threadQueueSize: 100

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: "http://10.1.11.46:10085/fsap-service-monitor/eureka/,http://10.1.11.64:10085/fsap-service-monitor/eureka/"
    registry-fetch-interval-seconds: 15
    refresh:
      enable: true
  instance:
    initial-status: STARTING
    metadata-map:
      gRPCPort: ${grpc.server.port}
    hostname: ${spring.application.name}
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15

#fsap:
#  client:
#    enable:
#      register: false
#      eureka: false
#  server:
#    monitor:
#      location: "http://10.1.11.46:10085/fsap-service-monitor/eureka/,http://10.1.11.64:10085/fsap-service-monitor/eureka/"

astar:
  binPath: "${rootPath}astar/"

request:
  FD: "${rootPath}FD/"

apiNodes: >
  apiNode_ANALY_S00.yml,
  apiNode_ANALY_S02.yml,
  apiNode_ANALY_S03.yml,
  apiNode_ANALY_S04.yml,
  apiNode_ANALY_S05.yml,
  apiNode_ANALY_S06.yml,
  apiNode_ANALY_S07.yml,
  apiNode_ANALY_S08.yml,
  apiNode_ANALY_S19.yml,
  apiNode_ANALY_S21.yml,
  apiNode_ANALY_S22.yml,
  apiNode_ANALY_S23.yml,
  apiNode_BT002.yml,
  apiNode_C0760.yml,
  apiNode_C1530_S01.yml,
  apiNode_C1530_S02.yml,
  apiNode_C1530_S03_01.yml,
  apiNode_C1530_S03_02.yml,
  apiNode_C1530_S04_01.yml,
  apiNode_C1530_S04_02.yml,
  apiNode_C1530_S05.yml,
  apiNode_C1530_S06.yml,
  apiNode_C1530_S07.yml,
  apiNode_C1530_S08.yml,
  apiNode_C1530_S09.yml,
  apiNode_C1530_S10.yml,
  apiNode_C1530_S11.yml,
  apiNode_C1530_S12.yml,
  apiNode_C1530_S13.yml,
  apiNode_C1530_S14.yml,
  apiNode_C1530_S15.yml,
  apiNode_C1530_S16.yml,
  apiNode_C1530_S17.yml,
  apiNode_C1530_S18.yml,
  apiNode_C1530_S19.yml,
  apiNode_C1530_S20.yml,
  apiNode_C1530_S21.yml,
  apiNode_C1530_S22.yml,
  apiNode_C1530_S23.yml,
  apiNode_C1530_S24.yml,
  apiNode_C1530_S25.yml,
  apiNode_C1530_S26.yml,
  apiNode_C1530_S27.yml,
  apiNode_C1530_S28.yml,
  apiNode_C1530_S29.yml,
  apiNode_C1530_S30.yml,
  apiNode_C1530_S31.yml,
  apiNode_C1530_S32.yml,
  apiNode_C1530_S33.yml,
  apiNode_C1530_S34.yml,
  apiNode_C1530_S35.yml,
  apiNode_C1530_S36.yml,
  apiNode_C1530_S36_02.yml,
  apiNode_C1530_S37.yml,
  apiNode_C1530_S38.yml,
  apiNode_C1530_S41.yml,
  apiNode_C1530_S42.yml,
  apiNode_C1530_S43.yml,
  apiNode_C1530_S43_02.yml,
  apiNode_C1530_S44.yml,
  apiNode_C1530_S45_01.yml,
  apiNode_C1530_S45_02.yml,
  apiNode_C1530_S46_01.yml,
  apiNode_C1530_S46_02.yml,
  apiNode_C1530_S46_03.yml,
  apiNode_C1530_S46_04.yml,
  apiNode_C1530_S46_05.yml,
  apiNode_C1530_S46_06.yml,
  apiNode_C1530_S47.yml,
  apiNode_C1530_S48.yml,
  apiNode_C1530_S49.yml,
  apiNode_C1530_S50_01.yml,
  apiNode_C1530_S50_02.yml,
  apiNode_C1530_S50_03.yml,
  apiNode_C1530_S51.yml,
  apiNode_C1530_S52.yml,
  apiNode_C1530_S53_01.yml,
  apiNode_C1530_S53_02.yml,
  apiNode_C1530_S53_03.yml,
  apiNode_C1530_S53_04.yml,
  apiNode_C1530_S54.yml,
  apiNode_C1530_S55.yml,
  apiNode_C1530_S56.yml,
  apiNode_C1530_S57.yml,
  apiNode_C1530_S58.yml,
  apiNode_C1530_S85_01.yml,
  apiNode_C1530_S85_05.yml,
  apiNode_C1530_S85_10.yml,
  apiNode_C1530_S86.yml,
  apiNode_C1530_S87.yml,
  apiNode_C1530_S89.yml,
  apiNode_C1530_S90.yml,
  apiNode_C1530_S91_01.yml,
  apiNode_C1530_S91_02.yml,
  apiNode_C1530_S91_03.yml,
  apiNode_CLADD.yml,
  apiNode_CLCMP.yml,
  apiNode_CLD03_S01.yml,
  apiNode_CLD03_S02.yml,
  apiNode_CLD03_S03.yml,
  apiNode_CLD04_S01.yml,
  apiNode_CLD04_S02.yml,
  apiNode_CLD11_S01.yml,
  apiNode_CLD12_S02.yml,
  apiNode_CLD12_S04.yml,
  apiNode_CLD20_S00.yml,
  apiNode_CLD22_S02.yml,
  apiNode_CLD22_S03.yml,
  apiNode_CLD22_S05.yml,
  apiNode_CLD22_S06.yml,
  apiNode_CLD22_S07.yml,
  apiNode_CLD23_S00.yml,
  apiNode_CLDTL_DWL.yml,
  apiNode_CLF00.yml,
  apiNode_CLF01.yml,
  apiNode_CLRFTP.yml,
  apiNode_NCL_PRTMSG.yml,
  apiNode_CLM01_S01.yml,
  apiNode_CLM01_S02.yml,
  apiNode_CLU01_S01.yml,
  apiNode_CLU01_S02.yml,
  apiNode_CLU01_S03.yml,
  apiNode_CONV27_S01.yml,
  apiNode_CONV27_S02.yml,
  apiNode_CONV27_S03.yml,
  apiNode_CONV511023_S02.yml,
  apiNode_CONV511023_S06.yml,
  apiNode_G2660.yml,
  apiNode_PRERU.yml,
  apiNode_PRETRUST_S01.yml,
  apiNode_PRETRUST_S02.yml,
  apiNode_STAT6_1B.yml,
  apiNode_STAT6_1C.yml,
  apiNode_STAT6_2A.yml,
  apiNode_STAT6_2B1.yml,
  apiNode_STAT6_2B2.yml,
  apiNode_STAT6_2C.yml,
  apiNode_STAT6_2D.yml,
  apiNode_STAT6_3A.yml,
  apiNode_STAT6_3B.yml,
  apiNode_STAT6_3C.yml,
  apiNode_STAT6_3F.yml,
  apiNode_STAT6_4A.yml,
  apiNode_STAT6_4B.yml,
  apiNode_STAT6_5.yml,
  apiNode_STAT6_5A.yml,
  apiNode_STAT6_5B.yml,
  apiNode_STAT6_5C.yml,
  apiNode_STAT6_5D.yml,
  apiNode_STAT6_5E.yml,
  apiNode_STAT6_6A.yml,
  apiNode_STAT6_6B2.yml,
  apiNode_STAT6_7A1.yml,
  apiNode_STAT6_7A2.yml,
  apiNode_STAT6_7A3.yml,
  apiNode_STAT6_7B1.yml,
  apiNode_STAT6_7B2.yml,
  apiNode_STAT6_7B3.yml,
  apiNode_STAT6_OKRTN.yml,
  apiNode_TXTEST.yml,
  apiNode_TF001.yml,
  apiNode_TF000.yml,
  apiNode_TFDEL.yml,
  apiNode_UPDCLCMP_S01.yml,
  apiNode_UPDCLCMP_S02.yml,
  apiNode_UPDCLCMP_S03.yml,
  apiNode_UPDCLCMP_S04.yml,
  apiNode_UPDCLCMP_S05.yml,
  apiNode_QUERYCLBAF_01.yml,
  apiNode_QUERYCLMR_01.yml,
  apiNode_QUERYCLDMR_01.yml,
  apiNode_QUERYCLMC_01.yml,
  apiNode_QUERYCLDTL_01.yml,
  apiNode_QUERYCLFEE_01.yml,
  apiNode_QUERYCLTOT_01.yml,
  apiNode_QUERYCLCMP_01.yml,
  apiNode_QUERYCLTMR_01.yml,
  apiNode_CRE_CLMR_01.yml,
  apiNode_CRE_CLDMR_01.yml,
  apiNode_CRE_CLCMP_01.yml,
  apiNode_TF004.yml,
  apiNode_CREAUO_S02.yml,
  apiNode_CVRPT.yml

localFile:
  ncl:
    batch:
      directory: "${rootPath}BH/"

fsapFile:
  gn:
    dwl:
      directory: "${rootPath}GN/DWL/"

externalSort:
  blockSize: 100000